# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "MaquinaVirtual1" do |mv1_config|
        mv1_config.vm.box = "ubuntu/xenial64"
        mv1_config.vm.network "forwarded_port", guest: 21474, host: 21474
        mv1_config.vm.boot_timeout = 10000
        config.vm.network "private_network", ip: "192.168.50.4",
            virtualbox__intnet: "mynetwork"
        mv1_config.vm.provider "virtualbox" do |vb|
            vb.name = "MaquinaVirtual1"
            vb.memory = "2048"
        end
        mv1_config.vm.provision "file", source: "./DockerFiles/DockerFileBack", destination: "Docker/rampupBackend"
        mv1_config.vm.provision "file", source: "./DockerFiles/DockerFileFront", destination: "Docker/rampupFrontend"
        mv1_config.vm.provision "shell", inline: <<-SHELL
            sudo apt update
            sudo apt upgrade -y
            sudo apt-get install -y curl apt-transport-https ca-certificates software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt update
            apt-cache policy docker-ce
            sudo apt install -y docker-ce
            mkdir Repositorio
            cd Repositorio
            git clone https://gitlab.com/matiasnicolas.vargas/schoolofdevopsdocker.git
            mv /home/vagrant/Docker/rampupBackend/dockerfile /home/vagrant/Repositorio/schoolofdevopsdocker/rampupBackend
            mv /home/vagrant/Docker/rampupFrontend/dockerfile /home/vagrant/Repositorio/schoolofdevopsdocker/rampupFrontend
        SHELL
    end
    config.vm.define "MaquinaVirtual2" do |mv2_config|
        mv2_config.vm.box = "ubuntu/xenial64"
        mv2_config.vm.network "forwarded_port", guest: 21475, host: 21475
        mv2_config.vm.boot_timeout = 10000
        config.vm.network "private_network", ip: "192.168.50.5",
            virtualbox__intnet: "mynetwork"
        mv2_config.vm.provider "virtualbox" do |vb|
            vb.name = "MaquinaVirtual2"
            vb.memory = "2048"
        end
        mv2_config.vm.provision "file", source: "./DockerFiles/DockerFileBack", destination: "Docker/rampupBackend"
        mv2_config.vm.provision "file", source: "./DockerFiles/DockerFileFront", destination: "Docker/rampupFrontend"
        mv2_config.vm.provision "shell", inline: <<-SHELL
            sudo apt update
            sudo apt upgrade -y
            sudo apt-get install -y curl apt-transport-https ca-certificates software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt update
            apt-cache policy docker-ce
            sudo apt install -y docker-ce
            mkdir Repositorio
            cd Repositorio
            git clone https://gitlab.com/matiasnicolas.vargas/schoolofdevopsdocker.git
            mv /home/vagrant/Docker/rampupBackend/dockerfile /home/vagrant/Repositorio/schoolofdevopsdocker/rampupBackend
            mv /home/vagrant/Docker/rampupFrontend/dockerfile /home/vagrant/Repositorio/schoolofdevopsdocker/rampupFrontend
            sudo service docker start
        SHELL
    end
end