# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = "Maquina-Tareas-SoD"
  end
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 21474, host: 21474
  config.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt upgrade -y
      sudo apt-get install -y curl apt-transport-https ca-certificates software-properties-common
  SHELL
end